import appleImg from "../../../assets/literacy-training-images/apple.png";
import ballImg from "../../../assets/literacy-training-images/ball.png";
import catImg from "../../../assets/literacy-training-images/cat.png";
import dogImg from "../../../assets/literacy-training-images/dog.png";
import eggImg from "../../../assets/literacy-training-images/egg.png";
import fishImg from "../../../assets/literacy-training-images/fish.png";
import goatImg from "../../../assets/literacy-training-images/goat.png";
import hatImg from "../../../assets/literacy-training-images/hat.png";
import iglooImg from "../../../assets/literacy-training-images/igloo.png";
import jamImg from "../../../assets/literacy-training-images/jam.png";
import kiteImg from "../../../assets/literacy-training-images/kite.png";
import lionImg from "../../../assets/literacy-training-images/lion.png";

export const englishPhonicsData = [
  {
    id: 1,
    letter: "A",
    syllableText: "Aa",
    wordText: "Apple",
    complexWord: "Ant",
    image: appleImg,
    color: "var(--card-red)",
  },
  {
    id: 2,
    letter: "B",
    syllableText: "Bb",
    wordText: "Ball",
    complexWord: "Bat",
    image: ballImg,
    color: "var(--card-blue)",
  },
  {
    id: 3,
    letter: "C",
    syllableText: "Cc",
    wordText: "Cat",
    complexWord: "Cat",
    image: catImg,
    color: "var(--card-yellow)",
  },
  {
    id: 4,
    letter: "D",
    syllableText: "Dd",
    wordText: "Dog",
    complexWord: "Dog",
    image: dogImg,
    color: "var(--card-green)",
  },
  {
    id: 5,
    letter: "E",
    syllableText: "Ee",
    wordText: "Egg",
    complexWord: "Egg",
    image: eggImg,
    color: "var(--card-orange)",
  },
  {
    id: 6,
    letter: "F",
    syllableText: "Ff",
    wordText: "Fish",
    complexWord: "Fan",
    image: fishImg,
    color: "var(--card-purple)",
  },
  {
    id: 7,
    letter: "G",
    syllableText: "Gg",
    wordText: "Goat",
    complexWord: "Gem",
    image: goatImg,
    color: "var(--card-pink)",
  },
  {
    id: 8,
    letter: "H",
    syllableText: "Hh",
    wordText: "Hat",
    complexWord: "Hat",
    image: hatImg,
    color: "var(--card-cyan)",
  },
  {
    id: 9,
    letter: "I",
    syllableText: "Ii",
    wordText: "Igloo",
    complexWord: "Ink",
    image: iglooImg,
    color: "var(--card-teal)",
  },
  {
    id: 10,
    letter: "J",
    syllableText: "Jj",
    wordText: "Jam",
    complexWord: "Jar",
    image: jamImg,
    color: "var(--card-lime)",
  },
  {
    id: 11,
    letter: "K",
    syllableText: "Kk",
    wordText: "Kite",
    complexWord: "Key",
    image: kiteImg,
    color: "var(--card-indigo)",
  },
  {
    id: 12,
    letter: "L",
    syllableText: "Ll",
    wordText: "Lion",
    complexWord: "Log",
    image: lionImg,
    color: "var(--card-amber)",
  },
  {
    id: 13,
    letter: "M",
    syllableText: "Mm",
    wordText: "Monkey",
    complexWord: "Mat",
    image: "https://placehold.co/300x300/ff6b6b/FFFFFF?text=Monkey",
    color: "var(--card-red)",
  },
  {
    id: 14,
    letter: "N",
    syllableText: "Nn",
    wordText: "Nest",
    complexWord: "Net",
    image: "https://placehold.co/300x300/4ecdc4/FFFFFF?text=Nest",
    color: "var(--card-blue)",
  },
  {
    id: 15,
    letter: "O",
    syllableText: "Oo",
    wordText: "Orange",
    complexWord: "Owl",
    image: "https://placehold.co/300x300/ffe66d/FFFFFF?text=Orange",
    color: "var(--card-yellow)",
  },
  {
    id: 16,
    letter: "P",
    syllableText: "Pp",
    wordText: "Parrot",
    complexWord: "Pen",
    image: "https://placehold.co/300x300/95e1d3/FFFFFF?text=Parrot",
    color: "var(--card-green)",
  },
  {
    id: 17,
    letter: "Q",
    syllableText: "Qq",
    wordText: "Queen",
    complexWord: "Quiz",
    image: "https://placehold.co/300x300/e0bbe4/FFFFFF?text=Queen",
    color: "var(--card-purple)",
  },
  {
    id: 18,
    letter: "R",
    syllableText: "Rr",
    wordText: "Rabbit",
    complexWord: "Rat",
    image: "https://placehold.co/300x300/957dad/FFFFFF?text=Rabbit",
    color: "var(--card-pink)",
  },
  {
    id: 19,
    letter: "S",
    syllableText: "Ss",
    wordText: "Sun",
    complexWord: "Sun",
    image: "https://placehold.co/300x300/ffdfd3/FFFFFF?text=Sun",
    color: "var(--card-orange)",
  },
  {
    id: 20,
    letter: "T",
    syllableText: "Tt",
    wordText: "Tiger",
    complexWord: "Toy",
    image: "https://placehold.co/300x300/fec8d8/FFFFFF?text=Tiger",
    color: "var(--card-red)",
  },
  {
    id: 21,
    letter: "U",
    syllableText: "Uu",
    wordText: "Umbrella",
    complexWord: "Urn",
    image: "https://placehold.co/300x300/d291bc/FFFFFF?text=Umbrella",
    color: "var(--card-blue)",
  },
  {
    id: 22,
    letter: "V",
    syllableText: "Vv",
    wordText: "Van",
    complexWord: "Van",
    image: "https://placehold.co/300x300/a0d2eb/FFFFFF?text=Van",
    color: "var(--card-cyan)",
  },
  {
    id: 23,
    letter: "W",
    syllableText: "Ww",
    wordText: "Watch",
    complexWord: "Web",
    image: "https://placehold.co/300x300/e5eec1/FFFFFF?text=Watch",
    color: "var(--card-lime)",
  },
  {
    id: 24,
    letter: "X",
    syllableText: "Xx",
    wordText: "Xylophone",
    complexWord: "Box",
    image: "https://placehold.co/300x300/b3cde0/FFFFFF?text=Xylophone",
    color: "var(--card-teal)",
  },
  {
    id: 25,
    letter: "Y",
    syllableText: "Yy",
    wordText: "Yak",
    complexWord: "Yak",
    image: "https://placehold.co/300x300/ffc1b6/FFFFFF?text=Yak",
    color: "var(--card-yellow)",
  },
  {
    id: 26,
    letter: "Z",
    syllableText: "Zz",
    wordText: "Zebra",
    complexWord: "Zip",
    image: "https://placehold.co/300x300/c5a3ff/FFFFFF?text=Zebra",
    color: "var(--card-indigo)",
  },
];

export const tamilPhonicsData = {
  uyir: [
    {
      id: 101,
      letter: "அ",
      syllableText: "அ",
      wordText: "அம்மா",
      complexWord: "அம்மா",
      image: "https://placehold.co/300x300/ff6b6b/FFFFFF?text=அ - அம்மா",
      color: "var(--card-red)",
    },
    {
      id: 102,
      letter: "ஆ",
      syllableText: "ஆ",
      wordText: "ஆடு",
      complexWord: "ஆடு",
      image: "https://placehold.co/300x300/4ecdc4/FFFFFF?text=ஆ - ஆடு",
      color: "var(--card-blue)",
    },
    {
      id: 103,
      letter: "இ",
      syllableText: "இ",
      wordText: "இலை",
      complexWord: "இலை",
      image: "https://placehold.co/300x300/ffe66d/FFFFFF?text=இ - இலை",
      color: "var(--card-yellow)",
    },
    {
      id: 104,
      letter: "ஈ",
      syllableText: "ஈ",
      wordText: "ஈ",
      complexWord: "ஈ",
      image: "https://placehold.co/300x300/95e1d3/FFFFFF?text=ஈ - ஈ",
      color: "var(--card-green)",
    },
    {
      id: 105,
      letter: "உ",
      syllableText: "உ",
      wordText: "உரல்",
      complexWord: "உரல்",
      image: "https://placehold.co/300x300/ff9f43/FFFFFF?text=உ - உரல்",
      color: "var(--card-orange)",
    },
    {
      id: 106,
      letter: "ஊ",
      syllableText: "ஊ",
      wordText: "ஊஞ்சல்",
      complexWord: "ஊஞ்சல்",
      image: "https://placehold.co/300x300/a29bfe/FFFFFF?text=ஊ - ஊஞ்சல்",
      color: "var(--card-purple)",
    },
    {
      id: 107,
      letter: "எ",
      syllableText: "எ",
      wordText: "எலி",
      complexWord: "எலி",
      image: "https://placehold.co/300x300/f7a8b8/FFFFFF?text=எ - எலி",
      color: "var(--card-pink)",
    },
    {
      id: 108,
      letter: "ஏ",
      syllableText: "ஏ",
      wordText: "ஏணி",
      complexWord: "ஏணி",
      image: "https://placehold.co/300x300/00d2d3/FFFFFF?text=ஏ - ஏணி",
      color: "var(--card-cyan)",
    },
    {
      id: 109,
      letter: "ஐ",
      syllableText: "ஐ",
      wordText: "ஐந்து",
      complexWord: "ஐந்து",
      image: "https://placehold.co/300x300/01a3a4/FFFFFF?text=ஐ - ஐந்து",
      color: "var(--card-teal)",
    },
    {
      id: 110,
      letter: "ஒ",
      syllableText: "ஒ",
      wordText: "ஒட்டகம்",
      complexWord: "ஒட்டகம்",
      image: "https://placehold.co/300x300/1dd1a1/FFFFFF?text=ஒ - ஒட்டகம்",
      color: "var(--card-lime)",
    },
    {
      id: 111,
      letter: "ஓ",
      syllableText: "ஓ",
      wordText: "ஓடம்",
      complexWord: "ஓடம்",
      image: "https://placehold.co/300x300/5f27cd/FFFFFF?text=ஓ - ஓடம்",
      color: "var(--card-indigo)",
    },
    {
      id: 112,
      letter: "ஔ",
      syllableText: "ஔ",
      wordText: "ஒளவையார்",
      complexWord: "ஔவை",
      image: "https://placehold.co/300x300/ff9ff3/FFFFFF?text=ஔ - ஒளவை",
      color: "var(--card-pink)",
    },
    {
      id: 113,
      letter: "ஃ",
      syllableText: "ஃ",
      wordText: "எஃகு",
      complexWord: "ஃ",
      image: "https://placehold.co/300x300/bdc3c7/FFFFFF?text=ஃ",
      color: "var(--card-grey)",
    },
  ],
  mei: [
    {
      id: 201,
      letter: "க்",
      syllableText: "க்",
      wordText: "சக்கரம்",
      complexWord: "க்",
      image: "https://placehold.co/300x300/ff6b6b/FFFFFF?text=க்",
      color: "var(--card-red)",
    },
    {
      id: 202,
      letter: "ங்",
      syllableText: "ங்",
      wordText: "சிங்கம்",
      complexWord: "ங்",
      image: "https://placehold.co/300x300/4ecdc4/FFFFFF?text=ங்",
      color: "var(--card-blue)",
    },
    {
      id: 203,
      letter: "ச்",
      syllableText: "ச்",
      wordText: "பச்சை",
      complexWord: "ச்",
      image: "https://placehold.co/300x300/ffe66d/FFFFFF?text=ச்",
      color: "var(--card-yellow)",
    },
    {
      id: 204,
      letter: "ஞ்",
      syllableText: "ஞ்",
      wordText: "மஞ்சள்",
      complexWord: "ஞ்",
      image: "https://placehold.co/300x300/95e1d3/FFFFFF?text=ஞ்",
      color: "var(--card-green)",
    },
    {
      id: 205,
      letter: "ட்",
      syllableText: "ட்",
      wordText: "பட்டம்",
      complexWord: "ட்",
      image: "https://placehold.co/300x300/ff9f43/FFFFFF?text=ட்",
      color: "var(--card-orange)",
    },
    {
      id: 206,
      letter: "ண்",
      syllableText: "ண்",
      wordText: "வண்டி",
      complexWord: "ண்",
      image: "https://placehold.co/300x300/a29bfe/FFFFFF?text=ண்",
      color: "var(--card-purple)",
    },
    {
      id: 207,
      letter: "த்",
      syllableText: "த்",
      wordText: "நத்தை",
      complexWord: "த்",
      image: "https://placehold.co/300x300/f7a8b8/FFFFFF?text=த்",
      color: "var(--card-pink)",
    },
    {
      id: 208,
      letter: "ந்",
      syllableText: "ந்",
      wordText: "பந்து",
      complexWord: "ந்",
      image: "https://placehold.co/300x300/00d2d3/FFFFFF?text=ந்",
      color: "var(--card-cyan)",
    },
    {
      id: 209,
      letter: "ப்",
      syllableText: "ப்",
      wordText: "கப்பல்",
      complexWord: "ப்",
      image: "https://placehold.co/300x300/01a3a4/FFFFFF?text=ப்",
      color: "var(--card-teal)",
    },
    {
      id: 210,
      letter: "ம்",
      syllableText: "ம்",
      wordText: "மரம்",
      complexWord: "ம்",
      image: "https://placehold.co/300x300/1dd1a1/FFFFFF?text=ம்",
      color: "var(--card-lime)",
    },
    {
      id: 211,
      letter: "ய்",
      syllableText: "ய்",
      wordText: "நாய்",
      complexWord: "ய்",
      image: "https://placehold.co/300x300/5f27cd/FFFFFF?text=ய்",
      color: "var(--card-indigo)",
    },
    {
      id: 212,
      letter: "ர்",
      syllableText: "ர்",
      wordText: "தேர்",
      complexWord: "ர்",
      image: "https://placehold.co/300x300/ff9ff3/FFFFFF?text=ர்",
      color: "var(--card-pink)",
    },
    {
      id: 213,
      letter: "ல்",
      syllableText: "ல்",
      wordText: "பல்",
      complexWord: "ல்",
      image: "https://placehold.co/300x300/bdc3c7/FFFFFF?text=ல்",
      color: "var(--card-red)",
    },
    {
      id: 214,
      letter: "வ்",
      syllableText: "வ்",
      wordText: "செவ்வாய்",
      complexWord: "வ்",
      image: "https://placehold.co/300x300/ff6b6b/FFFFFF?text=வ்",
      color: "var(--card-blue)",
    },
    {
      id: 215,
      letter: "ழ்",
      syllableText: "ழ்",
      wordText: "யாழ்",
      complexWord: "ழ்",
      image: "https://placehold.co/300x300/4ecdc4/FFFFFF?text=ழ்",
      color: "var(--card-yellow)",
    },
    {
      id: 216,
      letter: "ள்",
      syllableText: "ள்",
      wordText: "வாள்",
      complexWord: "ள்",
      image: "https://placehold.co/300x300/ffe66d/FFFFFF?text=ள்",
      color: "var(--card-green)",
    },
    {
      id: 217,
      letter: "ற்",
      syllableText: "ற்",
      wordText: "நாற்று",
      complexWord: "ற்",
      image: "https://placehold.co/300x300/95e1d3/FFFFFF?text=ற்",
      color: "var(--card-orange)",
    },
    {
      id: 218,
      letter: "ன்",
      syllableText: "ன்",
      wordText: "மீன்",
      complexWord: "ன்",
      image: "https://placehold.co/300x300/ff9f43/FFFFFF?text=ன்",
      color: "var(--card-blue)",
    },
  ],
  uyirMei: [], // Will be populated dynamically or via a large static list
};

// Programmatic generation of Uyir-Mei for completeness
const meiBase = [
  "க",
  "ங",
  "ச",
  "ஞ",
  "ட",
  "ண",
  "த",
  "ந",
  "ப",
  "ம",
  "ய",
  "ர",
  "ல",
  "வ",
  "ழ",
  "ள",
  "ற",
  "ன",
];
const uyirSuffixes = [
  "",
  "ா",
  "ி",
  "ீ",
  "ு",
  "ூ",
  "ெ",
  "ே",
  "ை",
  "ொ",
  "ோ",
  "ௌ",
];
const colors = [
  "var(--card-red)",
  "var(--card-blue)",
  "var(--card-yellow)",
  "var(--card-green)",
  "var(--card-orange)",
  "var(--card-purple)",
  "var(--card-pink)",
  "var(--card-cyan)",
  "var(--card-teal)",
  "var(--card-lime)",
  "var(--card-indigo)",
  "var(--card-amber)",
];

let idCounter = 301;
// Generate all 216 Uyir-Mei characters
meiBase.forEach((mei, mIdx) => {
  uyirSuffixes.forEach((suffix, sIdx) => {
    const char = mei + suffix;
    tamilPhonicsData.uyirMei.push({
      id: idCounter++,
      letter: char,
      syllableText: char,
      wordText: char,
      complexWord: char,
      image: `https://placehold.co/300x300/ffffff/000000?text=${char}`,
      color: colors[(mIdx + sIdx) % colors.length],
    });
  });
});

export const getPhonicsData = (lang, category = "uyir") => {
  if (lang === "en") return englishPhonicsData;
  if (lang === "ta") return tamilPhonicsData[category] || tamilPhonicsData.uyir;
  return englishPhonicsData;
};
